spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 155
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
app:
  module-name: Weapons
  api-version: 1
server:
  servlet:
    context-path: /api/v1
springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: /ui/
