spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 155
    driver-class-name: org.postgresql.Driver

server:
  servlet:
    context-path: /api/v1
